{{- $svc := include "lamassu.svc.merged" (dict "root" $ "svcKey" "alerts") | fromYaml -}}
{{ include "lamassu.httproute" (dict "root" $ "name" "api-alerts" "backend" "alerts" "port" $svc.port "path" "/api/alerts/" "rewrite" "/" "authLabel" "private") }}
