kind: ConfigMap
apiVersion: v1
metadata:
  name: alerts-config
  namespace: {{.Release.Namespace}}
data:
  config: |
    {{- include "lamassu.config.header" (dict "logsLevel" "debug" "healthCheck" false) | nindent 4 }}

    {{- include "lamassu.config.eventbus" (dict "root" $ "key" "subscriber_event_bus") | nindent 4 }}

    {{- include "lamassu.config.eventbus" (dict "root" $ "key" "subscriber_dlq_event_bus" "dlq" true) | nindent 4 }}

    {{- include "lamassu.config.storage" $ | nindent 4 }}

    authz_client:
      log_level: debug
      auth_mode: noauth
      protocol: http
      hostname: authz
      port: 8085
    
    smtp_server:
      from: {{ .Values.services.alerts.smtp_server.from }}
      host: {{ .Values.services.alerts.smtp_server.host }}
      port: {{ .Values.services.alerts.smtp_server.port }}
      username: {{ .Values.services.alerts.smtp_server.username }}
      password: {{ .Values.services.alerts.smtp_server.password }}
      ssl: {{ .Values.services.alerts.smtp_server.enable_ssl }}
      insecure: {{ .Values.services.alerts.smtp_server.insecure }}
    {{- include "lamassu.config.otel" $ | nindent 4 }}
