apiVersion: apps/v1
kind: Deployment
metadata:  
  name: api-gateway
  namespace: {{.Release.Namespace}}
  annotations:
    reloader.stakater.com/auto: "true"
  labels:
    app: api-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      initContainers:
        - name: init-tls-certs
          image: ghcr.io/lamassuiot/toolbox:dev
          imagePullPolicy: {{ .Values.global.imagePullPolicy | quote }}
          command: ["/bin/bash", "/docker-entrypoint.sh"]
          volumeMounts:
            - name: downstream-tls-certificate
              mountPath: /certs/downstream.crt
              subPath: tls.crt
            - name: downstream-tls-certificate
              mountPath: /certs/downstream-ca.crt
              subPath: ca.crt
            - name: envoy-config
              mountPath: /docker-entrypoint.sh   
              subPath: init-tls.sh  
            - name: shared
              mountPath: /shared
      containers:
        - name: api-gateway
          image: envoyproxy/envoy:v1.25-latest
          imagePullPolicy: {{ .Values.global.imagePullPolicy | quote }}
          tty: true          
          env:
            - name: DEBUG_MODE
              value: "{{.Values.debugMode}}"
          command: ["/bin/bash", "-c"]
          args: 
            - /docker-entrypoint.sh
          livenessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 3
            periodSeconds: 3
          volumeMounts:
            - name: envoy-config
              mountPath: /etc/envoy.yaml
              subPath: config.yml
            - name: envoy-config
              mountPath: /docker-entrypoint.sh
              subPath: init.sh
            - name: downstream-tls-certificate
              mountPath: /certs/downstream.key
              subPath: tls.key
            - name: shared
              mountPath: /shared
          ports:
            - name: http
              containerPort: 80
            - name: https
              containerPort: 443
            - name: stats
              containerPort: 9900
        
      restartPolicy: Always
      volumes:
        - name: downstream-tls-certificate
          secret:
            secretName:  {{ ternary .Values.tls.externalOptions.secretName  "downstream-cert" (eq .Values.tls.type "external") }}
        - name: envoy-config
          configMap:  
            name: api-gateway-config
            defaultMode: 480 #this value MUST be set in decimal NOT in octal
        - name: shared
          emptyDir: {}
