{{ range $instance := $.Values.services.connectors }}
{{- if eq $instance.type "awsiot" }}
{{- $instanceID := $instance.id | replace "aws." "" }}
{{ include "lamassu.pdb" (dict "root" $ "name" (printf "aws-connector-%s" $instanceID) "svc" $instance) }}
---
{{- end }}
{{- end }}
