{{- if .Values.services.awsConnector.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:  
  name: aws-connector
  namespace: {{.Release.Namespace}}
  annotations:
    reloader.stakater.com/auto: "true"
  labels:
    app: aws-connector
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aws-connector
  template:
    metadata:
      labels:
        app: aws-connector
    spec:
      containers:
        - name: aws-connector
          image: {{ .Values.services.awsConnector.image }}
          imagePullPolicy: Always
          tty: true         
          volumeMounts:
            - name: config
              mountPath: /etc/lamassuiot/config.yml
              subPath: config
          ports:
            - containerPort: 8085
      restartPolicy: Always
      volumes:
        - name: config
          configMap:  
            name: aws-connector-config
{{- end -}}

