{{ range $connectorID, $instance := $.Values.services.connectors }}
{{- if eq $instance.type "awsiot" }}
{{- $instanceID := $connectorID | replace "aws." "" }}
{{ include "lamassu.service" (dict "root" $ "name" (printf "aws-connector-%s" $instanceID) "svc" $instance) }}
---
{{- end -}}
{{- end -}}
