{{ range $instance := $.Values.services.connectors }}
{{- if eq $instance.type "awsiot" }}
{{- $instanceID := $instance.id | replace "aws." "" }}
{{ include "lamassu.workload" (dict
  "root" $
  "name" (printf "aws-connector-%s" $instanceID)
  "svc" $instance
  "configMapName" (printf "aws-connector-config-%s" $instanceID)) }}
---
{{- end -}}
{{- end -}}
