{{ range $instance := $.Values.services.connectors }}
{{- if eq $instance.type "awsiot" }}
{{ $instanceID := $instance.id | replace "aws." "" }}
kind: ConfigMap
apiVersion: v1
metadata:
  name: aws-connector-config-{{ $instanceID }}
  namespace: {{ $.Release.Namespace}}
data:
  config: |
    logs:
      level: "info"

    subscriber_event_bus:
      log_level: "debug"
      enabled: true
      provider: amqp
      protocol: amqp #amqp | amqps
      hostname: {{ $.Values.amqp.hostname }}
      port: {{ $.Values.amqp.port }}
      basic_auth:
        enabled: true
        username: {{ $.Values.amqp.username }}
        password: {{ $.Values.amqp.password }}
        
    subscriber_dlq_event_bus:
      log_level: "debug"
      enabled: true
      provider: amqp
      protocol: amqp #amqp | amqps
      hostname: {{ $.Values.amqp.hostname }}
      port: {{ $.Values.amqp.port }}
      exchange: lamassu-dlq
      basic_auth:
        enabled: true
        username: "{{ $.Values.amqp.username }}"
        password: "{{ $.Values.amqp.password }}"

    dms_manager_client:
      log_level: debug
      auth_mode: noauth
      protocol: http
      hostname: dms-manager
      port: 8085

    device_manager_client:
      log_level: debug
      auth_mode: noauth
      protocol: http
      hostname: device-manager
      port: 8085

    ca_client:
      log_level: debug
      auth_mode: noauth
      protocol: http
      hostname: ca
      port: 8085

    authz_client:
      log_level: debug
      auth_mode: noauth
      protocol: http
      hostname: authz
      port: 8085
      http_client:
        log_level: debug
        auth_mode: noauth
        http_connection:
          protocol: http
          basic_connection:
            hostname: authz
            port: 8085

    connector_id:  {{ $instance.id }}
    aws_config:
      {{ $instance.credentials | toYaml | indent 6 | trim  }}
{{ if $.Values.observability.enabled }}
    otel:
      traces:
        enabled: true
        hostname: {{ $.Values.observability.traces.hostname }}
        port: {{ $.Values.observability.traces.port }}
        scheme: {{ $.Values.observability.traces.scheme }}
        base_path: "{{ $.Values.observability.traces.basePath }}"
      logging:
        enabled: true
        hostname: {{ $.Values.observability.logs.hostname }}
        port: {{ $.Values.observability.logs.port }}
        scheme: {{ $.Values.observability.logs.scheme }}
        base_path: "{{ $.Values.observability.logs.basePath }}"
      metrics:
        enabled: false
{{ end }}
---
{{- end -}}
{{- end -}}
