{{ range $instance := $.Values.services.awsConnector.instances }}
{{ $instanceID := $instance.connectorID | replace "aws." "" }}
kind: ConfigMap
apiVersion: v1
metadata:
  name: aws-connector-config-{{ $instanceID }}
  namespace: {{ $.Release.Namespace}}
data:
  config: |
    logs:
      level: "info"

    subscriber_event_bus:
      log_level: "debug"
      provider: amqp
      enabled: true
      amqp:
        protocol: amqp #amqp | amqps
        hostname: {{ $.Values.amqp.hostname }}
        port: {{ $.Values.amqp.port }}
        basic_auth:
          enabled: true
          username: {{ $.Values.amqp.username }}
          password: {{ $.Values.amqp.password }}

    dms_manager_client:
      log_level: debug
      auth_mode: noauth
      protocol: http
      hostname: dms-manager
      port: 8085

    device_manager_client:
      log_level: debug
      auth_mode: noauth
      protocol: http
      hostname: device-manager
      port: 8085

    ca_client:
      log_level: debug
      auth_mode: noauth
      protocol: http
      hostname: ca
      port: 8085

    connector_id:  {{ $instance.connectorID }}
    aws_config:
      {{ $instance.credentials | toYaml | indent 6 | trim  }}
---
{{- end -}}
