{{ range $instance := $.Values.services.connectors }}
{{- if eq $instance.type "awsiot" }}
{{ $instanceID := $instance.id | replace "aws." "" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: aws-connector-{{ $instanceID }}
  namespace: {{ $.Release.Namespace}}
  annotations:
    reloader.stakater.com/auto: "true"
  labels:
    app: aws-connector-{{ $instanceID }}
spec:
  {{- if not (dig "autoscaling" "enabled" false $instance) }}
  replicas: {{ $instance.replicaCount | default 1 }}
  {{- end }}
  selector:
    matchLabels:
      app: aws-connector-{{ $instanceID }}
  template:
    metadata:
      labels:
        app: aws-connector-{{ $instanceID }}
    spec:
      containers:
        - name: aws-connector-{{ $instanceID }}
          image: {{ $instance.image }}
          imagePullPolicy: {{ $.Values.global.imagePullPolicy | quote }}
          tty: true
          livenessProbe:
            httpGet:
              path: /health
              port: 8085
            initialDelaySeconds: 3
            periodSeconds: 3
          readinessProbe:
            httpGet:
              path: /health
              port: 8085
            initialDelaySeconds: 3
            periodSeconds: 3
          volumeMounts:
            - name: config
              mountPath: /etc/lamassuiot/config.yml
              subPath: config
          ports:
            - containerPort: 8085
          {{- if $instance.resources }}
          resources:
            {{- toYaml $instance.resources | nindent 12 }}
          {{- end }}
      restartPolicy: Always
      volumes:
        - name: config
          configMap:
            name: aws-connector-config-{{ $instanceID }}
---
{{- end -}}
{{- end -}}
