{{ range $instance := $.Values.services.connectors }}
{{- if eq $instance.type "awsiot" }}
{{ $instanceID := $instance.id | replace "aws." "" }}
kind: ConfigMap
apiVersion: v1
metadata:
  name: aws-connector-config-{{ $instanceID }}
  namespace: {{ $.Release.Namespace}}
data:
  config: |
    logs:
      level: "info"

    {{- include "lamassu.config.eventbus" (dict "root" $ "key" "subscriber_event_bus") | nindent 4 }}

    {{- include "lamassu.config.eventbus" (dict "root" $ "key" "subscriber_dlq_event_bus" "dlq" true) | nindent 4 }}

    {{- include "lamassu.config.client" (dict "key" "dms_manager_client" "hostname" "dms-manager") | nindent 4 }}

    {{- include "lamassu.config.client" (dict "key" "device_manager_client" "hostname" "device-manager") | nindent 4 }}

    {{- include "lamassu.config.client" (dict "key" "ca_client" "hostname" "ca") | nindent 4 }}

    {{- include "lamassu.config.client" (dict "key" "authz_client" "hostname" "authz") | nindent 4 }}

    connector_id:  {{ $instance.id }}
    aws_config:
      {{ $instance.credentials | toYaml | indent 6 | trim  }}
    {{- include "lamassu.config.otel" $ | nindent 4 }}
---
{{- end -}}
{{- end -}}
