{{ range $instance := $.Values.services.connectors }}
{{- if eq $instance.type "awsiot" }}
{{ $instanceID := $instance.id | replace "aws." "" }}
kind: ConfigMap
apiVersion: v1
metadata:
  name: aws-connector-config-{{ $instanceID }}
  namespace: {{ $.Release.Namespace}}
data:
  config: |
    logs:
      level: "info"

    {{- include "lamassu.config.eventbus" (dict "root" $ "key" "subscriber_event_bus") | nindent 4 }}

    {{- include "lamassu.config.eventbus" (dict "root" $ "key" "subscriber_dlq_event_bus" "dlq" true) | nindent 4 }}

    dms_manager_client:
      log_level: debug
      auth_mode: noauth
      protocol: http
      hostname: dms-manager
      port: 8085

    device_manager_client:
      log_level: debug
      auth_mode: noauth
      protocol: http
      hostname: device-manager
      port: 8085

    ca_client:
      log_level: debug
      auth_mode: noauth
      protocol: http
      hostname: ca
      port: 8085

    authz_client:
      log_level: debug
      auth_mode: noauth
      protocol: http
      hostname: authz
      port: 8085

    connector_id:  {{ $instance.id }}
    aws_config:
      {{ $instance.credentials | toYaml | indent 6 | trim  }}
    {{- include "lamassu.config.otel" $ | nindent 4 }}
---
{{- end -}}
{{- end -}}
