{{- $svc := include "lamassu.svc.merged" (dict "root" $ "svcKey" "ca") | fromYaml -}}
kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ include "lamassu.componentName" (dict "root" $ "component" "ca-config") }}
  {{- include "lamassu.resourceMetadata" (dict "root" $ "component" "ca") | nindent 2 }}
data:
  config: |
    {{- include "lamassu.config.header" (dict "logsLevel" "debug" "healthCheck" false "port" $svc.port) | nindent 4 }}

    {{- include "lamassu.config.eventbus" (dict "root" $ "key" "publisher_event_bus") | nindent 4 }}

    {{- include "lamassu.config.storage" $ | nindent 4 }}

    kms_client:
      log_level: debug
      auth_mode: noauth
      protocol: http
      hostname: {{ include "lamassu.componentName" (dict "root" $ "component" "kms") }}
      port: {{ include "lamassu.config.servicePort" (dict "root" $ "svcKey" "kms") }}

    {{- include "lamassu.config.authzClient" $ | nindent 4 }}
    certificate_monitoring_job:
      enabled: true
      frequency: "{{ .Values.services.ca.monitoring.frequency }}"
      automatic_ca_rotation:
        enabled: false
        renewal_delta: "1d"

    va_server_domains:
    {{ range $.Values.services.ca.domains }}
      - "{{ . }}/api/va"
    {{ end }}
    {{- include "lamassu.config.otel" $ | nindent 4 }}
