kind: ConfigMap
apiVersion: v1
metadata:
  name: ca-config
  namespace: {{.Release.Namespace}}
data:
  config: |
    logs:
      level: "debug"

    server:
      log_level: "debug"
      health_check: false
      listen_address: "0.0.0.0"
      port: 8085
      protocol: "http" #http | https

    openapi:
      enabled: true
  
    publisher_event_bus:
      log_level: "debug"
      enabled: true
      provider: amqp
      protocol: amqp #amqp | amqps
      hostname: {{ $.Values.amqp.hostname }}
      port: {{ $.Values.amqp.port }}
      basic_auth:
        enabled: true
        username: {{ $.Values.amqp.username }}
        password: {{ $.Values.amqp.password }}

    storage:
      log_level: "{{ $.Values.postgres.logLevel }}"
      provider: "postgres" #couch_db | postgres | dynamo_db
      hostname: {{ $.Values.postgres.hostname }}
      port: {{ $.Values.postgres.port }}
      username: "{{ $.Values.postgres.username }}"
      password: "{{ $.Values.postgres.password }}"

    kms_client:
      log_level: debug
      auth_mode: noauth
      protocol: http
      hostname: kms
      port: 8085

    authz_client:
      log_level: debug
      auth_mode: noauth
      protocol: http
      hostname: authz
      port: 8085
        
    certificate_monitoring_job:
      enabled: true
      frequency: "{{ .Values.services.ca.monitoring.frequency }}"
      automatic_ca_rotation:
        enabled: false
        renewal_delta: "1d"
    
        
    va_server_domains:
    {{ range $.Values.services.ca.domains }}
      - "{{ . }}/api/va"
    {{ end }}
{{ if .Values.observability.enabled }}
    otel:
      traces:
        enabled: true
        hostname: {{ .Values.observability.traces.hostname }}
        port: {{ .Values.observability.traces.port }}
        scheme: {{ .Values.observability.traces.scheme }}
        base_path: "{{ .Values.observability.traces.basePath }}"
      logging:
        enabled: true
        hostname: {{ .Values.observability.logs.hostname }}
        port: {{ .Values.observability.logs.port }}
        scheme: {{ .Values.observability.logs.scheme }}
        base_path: "{{ .Values.observability.logs.basePath }}"
      metrics:
        enabled: false
{{ end }}