kind: ConfigMap
apiVersion: v1
metadata:
  name: ca-config
  namespace: {{.Release.Namespace}}
data:
  config: |
    {{- include "lamassu.config.header" (dict "logsLevel" "debug" "healthCheck" false) | nindent 4 }}

    {{- include "lamassu.config.eventbus" (dict "root" $ "key" "publisher_event_bus") | nindent 4 }}

    {{- include "lamassu.config.storage" $ | nindent 4 }}

    kms_client:
      log_level: debug
      auth_mode: noauth
      protocol: http
      hostname: kms
      port: 8085

    authz_client:
      log_level: debug
      auth_mode: noauth
      protocol: http
      hostname: authz
      port: 8085
        
    certificate_monitoring_job:
      enabled: true
      frequency: "{{ .Values.services.ca.monitoring.frequency }}"
      automatic_ca_rotation:
        enabled: false
        renewal_delta: "1d"

    va_server_domains:
    {{ range $.Values.services.ca.domains }}
      - "{{ . }}/api/va"
    {{ end }}
    {{- include "lamassu.config.otel" $ | nindent 4 }}
