{{- $svc := include "lamassu.svc.merged" (dict "root" $ "svcKey" "ca") | fromYaml -}}
{{ include "lamassu.httproute" (dict "root" $ "name" "api-ca" "backend" "ca" "port" $svc.port "path" "/api/ca/" "rewrite" "/" "authLabel" "private") }}
