{{- if .Values.services.ca.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: ca
  namespace: {{ .Release.Namespace }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ca
  minReplicas: {{ .Values.services.ca.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.services.ca.autoscaling.maxReplicas }}
  metrics:
    {{- if .Values.services.ca.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.services.ca.autoscaling.targetCPUUtilizationPercentage }}
    {{- end }}
    {{- if .Values.services.ca.autoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.services.ca.autoscaling.targetMemoryUtilizationPercentage }}
    {{- end }}
{{- end }}