{{- $svc := include "lamassu.svc.merged" (dict "root" $ "svcKey" "deviceManager") | fromYaml -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "lamassu.componentName" (dict "root" $ "component" "device-manager") }}
  {{- include "lamassu.resourceMetadata" (dict "root" $ "component" "device-manager") | nindent 2 }}
spec:
  selector:
    {{- include "lamassu.selectorLabels" (dict "root" $ "component" "device-manager") | nindent 4 }}
  type: ClusterIP
  ports:
    - name: http
      port: {{ $svc.port }}
      targetPort: {{ $svc.port }}
      protocol: TCP
