kind: ConfigMap
apiVersion: v1
metadata:
  name: device-manager-config
  namespace: {{.Release.Namespace}}
data:
  config: |
    {{- include "lamassu.config.header" (dict "logsLevel" "debug" "healthCheck" false "sse" true) | nindent 4 }}

    {{- include "lamassu.config.eventbus" (dict "root" $ "key" "subscriber_event_bus") | nindent 4 }}

    {{- include "lamassu.config.eventbus" (dict "root" $ "key" "subscriber_dlq_event_bus" "dlq" true) | nindent 4 }}

    {{- include "lamassu.config.eventbus" (dict "root" $ "key" "publisher_event_bus") | nindent 4 }}

    {{- include "lamassu.config.storage" $ | nindent 4 }}

    {{- include "lamassu.config.client" (dict "key" "device_manager_client" "hostname" "device-manager") | nindent 4 }}

    {{- include "lamassu.config.client" (dict "key" "ca_client" "hostname" "ca") | nindent 4 }}

    {{- include "lamassu.config.client" (dict "key" "authz_client" "hostname" "authz") | nindent 4 }}
    {{- include "lamassu.config.otel" $ | nindent 4 }}
