{{- $svc := include "lamassu.svc.merged" (dict "root" $ "svcKey" "deviceManager") | fromYaml -}}
kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ include "lamassu.componentName" (dict "root" $ "component" "device-manager-config") }}
  {{- include "lamassu.resourceMetadata" (dict "root" $ "component" "device-manager") | nindent 2 }}
data:
  config: |
    {{- include "lamassu.config.header" (dict "logsLevel" "debug" "healthCheck" false "port" $svc.port "sse" true) | nindent 4 }}

    {{- include "lamassu.config.eventbus" (dict "root" $ "key" "subscriber_event_bus") | nindent 4 }}

    {{- include "lamassu.config.eventbus" (dict "root" $ "key" "subscriber_dlq_event_bus" "dlq" true) | nindent 4 }}

    {{- include "lamassu.config.eventbus" (dict "root" $ "key" "publisher_event_bus") | nindent 4 }}

    {{- include "lamassu.config.storage" $ | nindent 4 }}

    device_manager_client:
      log_level: debug
      auth_mode: noauth
      protocol: http
      hostname: {{ include "lamassu.componentName" (dict "root" $ "component" "device-manager") }}
      port: {{ $svc.port }}

    ca_client:
      log_level: debug
      auth_mode: noauth
      protocol: http
      hostname: {{ include "lamassu.componentName" (dict "root" $ "component" "ca") }}
      port: {{ include "lamassu.config.servicePort" (dict "root" $ "svcKey" "ca") }}
    {{- include "lamassu.config.authzClient" $ | nindent 4 }}
    {{- include "lamassu.config.otel" $ | nindent 4 }}
