kind: ConfigMap
apiVersion: v1
metadata:
  name: device-manager-config
  namespace: {{.Release.Namespace}}
data:
  config: |
    {{- include "lamassu.config.header" (dict "logsLevel" "debug" "healthCheck" false "sse" true) | nindent 4 }}

    {{- include "lamassu.config.eventbus" (dict "root" $ "key" "subscriber_event_bus") | nindent 4 }}

    {{- include "lamassu.config.eventbus" (dict "root" $ "key" "subscriber_dlq_event_bus" "dlq" true) | nindent 4 }}

    {{- include "lamassu.config.eventbus" (dict "root" $ "key" "publisher_event_bus") | nindent 4 }}

    {{- include "lamassu.config.storage" $ | nindent 4 }}

    device_manager_client:
      log_level: debug
      auth_mode: noauth
      protocol: http
      hostname: device-manager
      port: 8085

    ca_client:
      log_level: debug
      auth_mode: noauth
      protocol: http
      hostname: ca
      port: 8085
    authz_client:
      log_level: debug
      auth_mode: noauth
      protocol: http
      hostname: authz
      port: 8085
      http_client:
        log_level: debug
        auth_mode: noauth
        http_connection:
          protocol: http
          basic_connection:
            hostname: authz
            port: 8085
    {{- include "lamassu.config.otel" $ | nindent 4 }}
