apiVersion: apps/v1
kind: Deployment
metadata:  
  name: device-manager
  namespace: {{.Release.Namespace}}
  annotations:
    reloader.stakater.com/auto: "true"
  labels:
    app: device-manager
spec:
  {{- if not .Values.services.deviceManager.autoscaling.enabled }}
  replicas: {{ .Values.services.deviceManager.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      app: device-manager
  template:
    metadata:
      labels:
        app: device-manager
    spec:
      containers:
        - name: device-manager
          image: {{ .Values.services.deviceManager.image }}
          imagePullPolicy: {{ .Values.global.imagePullPolicy | quote }}
          tty: true
          livenessProbe:
            httpGet:
              path: /health
              port: 8085
            initialDelaySeconds: 3
            periodSeconds: 3
          readinessProbe:
            httpGet:
              path: /health
              port: 8085
            initialDelaySeconds: 3
            periodSeconds: 3
          volumeMounts:
            - name: api-config
              mountPath: /etc/lamassuiot/config.yml
              subPath: config
          ports:
            - containerPort: 8085
      restartPolicy: Always
      {{- if .Values.services.deviceManager.affinity }}
      affinity:
        {{- toYaml .Values.services.deviceManager.affinity | nindent 8 }}
      {{- else }}
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app: device-manager
                topologyKey: kubernetes.io/hostname
      {{- end }}
      {{- if .Values.services.deviceManager.topologySpreadConstraints }}
      topologySpreadConstraints:
        {{- toYaml .Values.services.deviceManager.topologySpreadConstraints | nindent 8 }}
      {{- else }}
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: topology.kubernetes.io/zone
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:
            matchLabels:
              app: device-manager
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:
            matchLabels:
              app: device-manager
      {{- end }}
      volumes:
        - name: api-config
          configMap:  
            name: device-manager-config
