{{ include "lamassu.workload" (dict
  "root" $
  "name" "dms-manager"
  "svcKey" "dmsManager"
  "initContainers" (include "lamassu.dmsManager.initContainers" $)
  "volumeMounts" (include "lamassu.dmsManager.volumeMounts" $)
  "volumes" (include "lamassu.dmsManager.volumes" $)) }}
