{{- if gt (int (ternary .Values.services.dmsManager.autoscaling.minReplicas .Values.services.dmsManager.replicaCount .Values.services.dmsManager.autoscaling.enabled)) 1 }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: dms-manager
  namespace: {{ .Release.Namespace }}
spec:
  minAvailable: {{ .Values.services.dmsManager.pdb.minAvailable }}
  selector:
    matchLabels:
      app: dms-manager
{{- end }}
