{{- if .Values.services.dmsManager.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: dms-manager
  namespace: {{ .Release.Namespace }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: dms-manager
  minReplicas: {{ .Values.services.dmsManager.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.services.dmsManager.autoscaling.maxReplicas }}
  metrics:
    {{- if .Values.services.dmsManager.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.services.dmsManager.autoscaling.targetCPUUtilizationPercentage }}
    {{- end }}
    {{- if .Values.services.dmsManager.autoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.services.dmsManager.autoscaling.targetMemoryUtilizationPercentage }}
    {{- end }}
{{- end }}
