apiVersion: apps/v1
kind: Deployment
metadata:  
  name: dms-manager
  namespace: {{.Release.Namespace}}
  annotations:
    reloader.stakater.com/auto: "true"
  labels:
    app: dms-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dms-manager
  template:
    metadata:
      labels:
        app: dms-manager
    spec:
      initContainers:
        - name: init-tls-certs
          image: ghcr.io/lamassuiot/toolbox:dev
          imagePullPolicy: {{ .Values.global.imagePullPolicy | quote }}
          command: ["/bin/bash", "/docker-entrypoint.sh"]
          volumeMounts:
            - name: downstream-tls-certificate
              mountPath: /certs/downstream.crt
              subPath: tls.crt
            - name: downstream-tls-certificate
              mountPath: /certs/downstream-ca.crt
              subPath: ca.crt
            - name: api-config
              mountPath: /docker-entrypoint.sh   
              subPath: init.sh
            - name: shared
              mountPath: /shared
      containers:
        - name: dms-manager
          image: {{ .Values.services.dmsManager.image }}
          imagePullPolicy: {{ .Values.global.imagePullPolicy | quote }}
          tty: true
          livenessProbe:
            httpGet:
              path: /health
              port: 8085
            initialDelaySeconds: 3
            periodSeconds: 3
          volumeMounts:
            - name: api-config
              mountPath: /etc/lamassuiot/config.yml
              subPath: config
            - name: shared
              mountPath: /shared
          ports:
            - containerPort: 8085
      restartPolicy: Always
      volumes:
        - name: api-config
          configMap:  
            name: dms-manager-config
        - name: downstream-tls-certificate
          secret:
            secretName:  {{ ternary .Values.tls.externalOptions.secretName  "downstream-cert" (eq .Values.tls.type "external") }}
        - name: shared
          emptyDir: {}