kind: ConfigMap
apiVersion: v1
metadata:
  name: dms-manager-config
  namespace: {{.Release.Namespace}}
data:
  init.sh: |
    #!/bin/bash
    BLUE='\033[0;34m'
    GREEN='\033[0;32m'
    ORANGE='\033[0;33m'
    RED='\033[0;31m'
    NOCOLOR='\033[0m'

    # The bundle certificate file
    BUNDLE_CRT_FILE=/shared/bundle.crt

    # The output root certificate file
    ROOT_CA_CRT_FILE=/shared/root.crt

    touch $BUNDLE_CRT_FILE

    echo -e "${BLUE}Bundling certificates...${NOCOLOR}"
    if [ ! -f /certs/downstream.crt ]; then
      echo -e "${RED}downstream.crt not found!${NOCOLOR}"
      exit 1
    else
      cat /certs/downstream.crt > $BUNDLE_CRT_FILE
    fi

    if [ -f /certs/downstream-ca.crt ]; then
      echo -e "${GREEN}downstream-ca.crt found!${NOCOLOR}"
      cat /certs/downstream-ca.crt >> $BUNDLE_CRT_FILE
    else
      echo -e "${ORANGE}downstream-ca.crt not found!${NOCOLOR}"
    fi

    echo -e "${BLUE}Printing certificate bundle...${NOCOLOR}"
    cat $BUNDLE_CRT_FILE

    echo -e "${BLUE}Extracting root (lowest hierarchy cert in bundle)...${NOCOLOR}"
    touch $ROOT_CA_CRT_FILE

    # Count the number of certificates in the bundle
    CERT_COUNT=$(grep -c 'END CERTIFICATE' $BUNDLE_CRT_FILE)

    # Extract the root certificate
    awk "BEGIN {p=0;} /BEGIN CERTIFICATE/ {p++;} p==$CERT_COUNT" $BUNDLE_CRT_FILE > $ROOT_CA_CRT_FILE

    echo "Root CA certificate has been extracted to $ROOT_CA_CRT_FILE"
    echo -e "${GREEN}Certificate Root extracted!${NOCOLOR}"
    cat $ROOT_CA_CRT_FILE

  config: |
    {{- include "lamassu.config.header" (dict "logsLevel" "trace" "healthCheck" false) | nindent 4 }}

    {{- include "lamassu.config.eventbus" (dict "root" $ "key" "publisher_event_bus") | nindent 4 }}

    {{- include "lamassu.config.storage" $ | nindent 4 }}

    {{- include "lamassu.config.client" (dict "key" "device_manager_client" "hostname" "device-manager") | nindent 4 }}

    {{- include "lamassu.config.client" (dict "key" "ca_client" "hostname" "ca") | nindent 4 }}

    {{- include "lamassu.config.client" (dict "key" "authz_client" "hostname" "authz") | nindent 4 }}

    downstream_cert_file: /shared/root.crt
    {{- include "lamassu.config.otel" $ | nindent 4 }}
