{{- $svc := include "lamassu.svc.merged" (dict "root" $ "svcKey" "dmsManager") | fromYaml -}}
{{- if $svc.autoscaling.enabled }}
{{- include "lamassu.autoscaling.validate" (dict "name" "dms-manager" "autoscaling" $svc.autoscaling) }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "lamassu.componentName" (dict "root" $ "component" "dms-manager") }}
  {{- include "lamassu.resourceMetadata" (dict "root" $ "component" "dms-manager") | nindent 2 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "lamassu.componentName" (dict "root" $ "component" "dms-manager") }}
  minReplicas: {{ $svc.autoscaling.minReplicas }}
  maxReplicas: {{ $svc.autoscaling.maxReplicas }}
  metrics:
    {{- include "lamassu.autoscaling.metrics" $svc.autoscaling | nindent 4 }}
{{- end }}
