apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "lamassu.componentName" (dict "root" $ "component" "root-downstream-cert") }}
  {{- include "lamassu.resourceMetadata" (dict "root" $ "component" "tls") | nindent 2 }}
spec:
  isCA: true
  {{- if .Values.tls.certManagerOptions.certSpec.duration}}
  duration: {{.Values.tls.certManagerOptions.certSpec.duration}}
  {{- end}}
  commonName: "downstream-selfsigned-cert"
  secretName: {{ include "lamassu.componentName" (dict "root" $ "component" "root-downstream-cert") }}
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: {{ include "lamassu.componentName" (dict "root" $ "component" "selfsigned-issuer") }}
    kind: Issuer
    group: cert-manager.io
