apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ include "lamassu.componentName" (dict "root" $ "component" "downstream-ca-selfsigned-issuer") }}
  {{- include "lamassu.resourceMetadata" (dict "root" $ "component" "tls") | nindent 2 }}
spec:
  ca:
    secretName: {{ include "lamassu.componentName" (dict "root" $ "component" "root-downstream-cert") }}
