{{- if or .Values.gateway.responseOverride.unauthorized.enabled .Values.gateway.responseOverride.forbidden.enabled }}
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: BackendTrafficPolicy
metadata:
  name: response-override
  namespace: {{ .Release.Namespace }}
spec:
  targetRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: eg
  responseOverride:
{{- if .Values.gateway.responseOverride.unauthorized.enabled }}
    - match:
        statusCodes:
          - type: Value
            value: 401
      response:
        contentType: {{ .Values.gateway.responseOverride.unauthorized.contentType | quote }}
        body:
          type: Inline
          inline: {{ .Values.gateway.responseOverride.unauthorized.body | quote }}
{{- end }}
{{- if .Values.gateway.responseOverride.forbidden.enabled }}
    - match:
        statusCodes:
          - type: Value
            value: 403
      response:
        contentType: {{ .Values.gateway.responseOverride.forbidden.contentType | quote }}
        body:
          type: Inline
          inline: {{ .Values.gateway.responseOverride.forbidden.body | quote }}
{{- end }}
{{- end }}
