{{- if .Values.auth.externalAuthorization.enabled }}
{{- $authz := include "lamassu.svc.merged" (dict "root" $ "svcKey" "authz") | fromYaml }}
{{- $servicePort := .Values.auth.externalAuthorization.servicePort | default $authz.port }}
{{- $serviceName := .Values.auth.externalAuthorization.serviceName | default (include "lamassu.componentName" (dict "root" $ "component" "authz")) }}
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: SecurityPolicy
metadata:
  name: {{ include "lamassu.componentName" (dict "root" $ "component" "external-authz") }}
  {{- include "lamassu.resourceMetadata" (dict "root" $ "component" "authz") | nindent 2 }}
spec:
  targetSelectors:
  - group: gateway.networking.k8s.io
    kind: HTTPRoute
    matchLabels:
      auth: "external"
  extAuth:
    failOpen: {{ .Values.auth.externalAuthorization.failOpen }}
    http:
      backendRefs:
        - name: {{ $serviceName }}
          port: {{ $servicePort }}
      path: {{ .Values.auth.externalAuthorization.path | quote }}
{{- end }}
