apiVersion: gateway.envoyproxy.io/v1alpha1
kind: SecurityPolicy
metadata:
  name: jwt-authn
  namespace: {{ .Release.Namespace }}
spec:
  targetSelectors:
  - group: gateway.networking.k8s.io
    kind: HTTPRoute
    matchLabels:
      auth: "private"
  cors:
    allowOrigins:
    - "*"
    allowHeaders:
    - "*"	
    allowMethods:
    - "*"
    allowCredentials: true
  jwt:
    providers:
    {{- range $.Values.auth.oidc.apiGateway.jwks }}
      - name: {{ .name }}
        remoteJWKS:
          uri: "{{ .uri }}"
    {{- end }}
    
  authorization:
    defaultAction: Deny
    rules:
    {{- range $.Values.auth.oidc.apiGateway.jwks }}
     - name: "allow"
       action: Allow
       principal:
        jwt:
          provider: {{ .name }}
          claims:
          - name: {{ $.Values.auth.authorization.rolesClaim }}
            valueType: StringArray
            values: ["{{ $.Values.auth.authorization.roles.admin }}"]
    {{- end }}
    
