apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyProxy
metadata:
  name: proxy
spec:
  provider:
    type: Kubernetes
    kubernetes:
      envoyService:
        allocateLoadBalancerNodePorts: false
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: eg
  namespace: {{ .Release.Namespace }}
spec:
  gatewayClassName: eg
  infrastructure:
    parametersRef:
      group: gateway.envoyproxy.io
      kind: EnvoyProxy
      name: proxy
  addresses:
  {{ range $ip := $.Values.gateway.addresses }}
  - type: IPAddress
    value: {{ $ip }}
  {{ end }}
  listeners:
    - name: http 
      protocol: HTTP
      port: {{ .Values.gateway.ports.http }}
    - name: https # Do not change. The EnvoyPatchPolicy is looking for this name to apply the patch.
      protocol: HTTPS
      port:  {{ .Values.gateway.ports.https }}
      tls:
        mode: Terminate
        certificateRefs:
        - kind: Secret
          group: ""
          name:  {{ ternary .Values.tls.externalOptions.secretName  "downstream-cert" (eq .Values.tls.type "external") }}
---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: ClientTrafficPolicy
metadata:
  name: enable-mtls
  namespace: {{ .Release.Namespace }}
spec:
  targetRefs:
  - group: gateway.networking.k8s.io
    kind: Gateway
    name: eg
  tls:
    maxVersion: "1.3"
    clientValidation: 
      optional: true
      mode: Request
  headers:
    xForwardedClientCert:
      mode: AppendForward
      certDetailsToAdd: 
      - Chain