apiVersion: gateway.envoyproxy.io/v1alpha1
kind: SecurityPolicy
metadata:
  name: jwt-authn
  namespace: {{ .Release.Namespace }}
spec:
  targetSelectors:
  - group: gateway.networking.k8s.io
    kind: HTTPRoute
    matchLabels:
      auth: "private"
  cors:
    allowOrigins:
    - "*"
    allowHeaders:
    - "*"	
    allowMethods:
    - "*"
    allowCredentials: true