{{- $svc := include "lamassu.svc.merged" (dict "root" $ "svcKey" "dmsManager") | fromYaml -}}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ include "lamassu.componentName" (dict "root" $ "component" "global-est") }}
  {{- include "lamassu.resourceMetadata" (dict "root" $ "component" "global-est" "extra" (dict "auth" "public")) | nindent 2 }}
spec:
  parentRefs:
    {{- include "lamassu.gatewayParentRef" (dict "root" $) | nindent 4 }}
  rules:
    - matches:
      - path:
          type: PathPrefix
          value: /.well-known/est
      backendRefs:
        - name: {{ include "lamassu.componentName" (dict "root" $ "component" "dms-manager") }}
          port: {{ $svc.port }}
