{{- $svc := include "lamassu.svc.merged" (dict "root" $ "svcKey" "dmsManager") | fromYaml -}}
{{ include "lamassu.httproute" (dict "root" $ "name" "global-est" "backend" "dms-manager" "port" $svc.port "path" "/.well-known/est" "authLabel" "public") }}
