{{- $svc := include "lamassu.svc.merged" (dict "root" $ "svcKey" "kms") | fromYaml -}}
{{ include "lamassu.httproute" (dict "root" $ "name" "api-kms" "backend" "kms" "port" $svc.port "path" "/api/kms/" "rewrite" "/" "authLabel" "private") }}
