{{- if .Values.services.kms.autoscaling.enabled }}
{{- $hasFilesystemEngine := include "kms.hasFilesystemEngine" . | eq "true" -}}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: kms
  namespace: {{ .Release.Namespace }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: {{ if $hasFilesystemEngine }}StatefulSet{{ else }}Deployment{{ end }}
    name: kms
  minReplicas: {{ .Values.services.kms.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.services.kms.autoscaling.maxReplicas }}
  metrics:
    {{- if .Values.services.kms.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.services.kms.autoscaling.targetCPUUtilizationPercentage }}
    {{- end }}
    {{- if .Values.services.kms.autoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.services.kms.autoscaling.targetMemoryUtilizationPercentage }}
    {{- end }}
{{- end }}
