{{- if gt (int (ternary .Values.services.kms.autoscaling.minReplicas .Values.services.kms.replicaCount .Values.services.kms.autoscaling.enabled)) 1 }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: kms
  namespace: {{ .Release.Namespace }}
spec:
  minAvailable: {{ .Values.services.kms.pdb.minAvailable }}
  selector:
    matchLabels:
      app: kms
{{- end }}
