kind: ConfigMap
apiVersion: v1
metadata:
  name: kms-config
  namespace: {{.Release.Namespace}}
data:
  config: |
    {{- include "lamassu.config.header" (dict "logsLevel" "debug" "healthCheck" false) | nindent 4 }}

    {{- include "lamassu.config.eventbus" (dict "root" $ "key" "publisher_event_bus") | nindent 4 }}

    {{- include "lamassu.config.storage" $ | nindent 4 }}

    authz_client:
      log_level: debug
      auth_mode: noauth
      protocol: http
      hostname: authz
      port: 8085
      http_client:
        log_level: debug
        auth_mode: noauth
        http_connection:
          protocol: http
          basic_connection:
            hostname: authz
            port: 8085

    crypto_engines:
      migrate_keys_format: false
      log_level: "trace"
      default_id: {{ .Values.services.kms.cryptoEngines.defaultEngineID }}
      engines:
        {{ .Values.services.kms.cryptoEngines.engines | toYaml | indent 4 | nindent 4 | trim  }}
    {{- include "lamassu.config.otel" $ | nindent 4 }}
