{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "lamassu.serviceAccountName" . }}
  labels:
    {{- include "lamassu.labels" (dict "root" . "component" "service-account") | nindent 4 }}
  {{- with (include "lamassu.annotations" (dict "root" . "extra" .Values.serviceAccount.annotations)) }}
  annotations:
    {{- . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.serviceAccount.automountServiceAccountToken }}
{{- end }}
