kind: ConfigMap
apiVersion: v1
metadata:
  name: va-config
  namespace: {{.Release.Namespace}}
data:
  config: |
    {{- include "lamassu.config.header" (dict "logsLevel" "info") | nindent 4 }}

    {{- if eq .Values.services.va.fileStore.type "local" }}
    filesystem_storage:
      id: "{{ .Values.services.va.fileStore.id }}"
      type: "{{ .Values.services.va.fileStore.type }}"
      storage_directory: "{{ .Values.services.va.fileStore.local.storageDirectory }}"
    {{- else if eq .Values.services.va.fileStore.type "s3" }}
    filesystem_storage:
      id: "{{ .Values.services.va.fileStore.id }}"
      type: "{{ .Values.services.va.fileStore.type }}"
      {{- toYaml (.Values.services.va.fileStore.s3 | default dict) | nindent 6 }}
    {{- end }}

    crl_monitoring_job:
      enabled: true
      frequency: "{{ .Values.services.va.job.crl.frequency }}"

    va_domains:
    {{ range $.Values.services.ca.domains }}
      - "{{ . }}/api/va"
    {{ end }}
    {{- include "lamassu.config.eventbus" (dict "root" $ "key" "subscriber_event_bus") | nindent 4 }}

    {{- include "lamassu.config.eventbus" (dict "root" $ "key" "subscriber_dlq_event_bus" "dlq" true) | nindent 4 }}

    {{- include "lamassu.config.eventbus" (dict "root" $ "key" "publisher_event_bus") | nindent 4 }}

    {{- include "lamassu.config.storage" $ | nindent 4 }}

    kms_client:
      log_level: debug
      auth_mode: noauth
      protocol: http
      hostname: kms
      port: 8085

    ca_client:
      log_level: debug
      auth_mode: "noauth"
      protocol: "http"
      hostname: "ca"
      port: 8085
    authz_client:
      log_level: debug
      auth_mode: noauth
      protocol: http
      hostname: authz
      port: 8085
      http_client:
        log_level: debug
        auth_mode: noauth
        http_connection:
          protocol: http
          basic_connection:
            hostname: authz
            port: 8085
    {{- include "lamassu.config.otel" $ | nindent 4 }}
