kind: ConfigMap
apiVersion: v1
metadata:
  name: va-config
  namespace: {{.Release.Namespace}}
data:
  config: |
    logs:
      level: "info" #info | debug | trace | none

    server:
      log_level: "debug"
      listen_address: "0.0.0.0"
      port: 8085
      protocol: "http" #http | https
      
    filesystem_storage:
      id: "{{ .Values.services.va.fileStore.id }}"
      type: "{{ .Values.services.va.fileStore.type }}"
      storage_directory: "{{ .Values.services.va.fileStore.storageDirectory }}"
    
    crl_monitoring_job:
      enabled: true
      frequency: "{{ .Values.services.va.job.crl.frequency }}"

    va_domains:
    {{ range $.Values.services.ca.domains }}
      - "{{ . }}/api/va"
    {{ end }}

    subscriber_event_bus:
      log_level: "debug"
      enabled: true
      provider: amqp
      protocol: amqp #amqp | amqps
      hostname: {{ .Values.amqp.hostname }}
      port: {{ .Values.amqp.port }}
      basic_auth:
        enabled: true
        username: "{{ .Values.amqp.username }}"
        password: "{{ .Values.amqp.password }}"
    
    publisher_event_bus:
      log_level: "debug"
      enabled: true
      provider: amqp
      protocol: amqp #amqp | amqps
      hostname: {{ .Values.amqp.hostname }}
      port: {{ .Values.amqp.port }}
      basic_auth:
        enabled: true
        username: "{{ .Values.amqp.username }}"
        password: "{{ .Values.amqp.password }}"

    storage:
      log_level: "info"
      provider: "postgres" 
      hostname: {{ $.Values.postgres.hostname }}
      port: {{ $.Values.postgres.port }}
      username: "{{ $.Values.postgres.username }}"
      password: "{{ $.Values.postgres.password }}"

    ca_client:
      log_level: debug
      auth_mode: "noauth"
      protocol: "http"
      hostname: "ca"
      port: 8085