{{- $svc := include "lamassu.svc.merged" (dict "root" $ "svcKey" "va") | fromYaml -}}
{{ include "lamassu.httproute" (dict "root" $ "name" "api-va" "backend" "va" "port" $svc.port "path" "/api/va/" "rewrite" "/" "sections" (list "http" "https")) }}
