apiVersion: apps/v1
kind: StatefulSet
metadata:  
  name: va
  namespace: {{.Release.Namespace}}
  annotations:
    reloader.stakater.com/auto: "true"
  labels:
    app: va
spec:
  replicas: 1
  selector:
    matchLabels:
      app: va
  template:
    metadata:
      labels:
        app: va
    spec:     
      containers:
        - name: va
          image: {{.Values.services.va.image}}
          imagePullPolicy: {{ .Values.global.imagePullPolicy | quote }}
          tty: true
          livenessProbe:
            httpGet:
              path: /health
              port: 8085
            initialDelaySeconds: 3
            periodSeconds: 3
          volumeMounts:
            - name: api-config
              mountPath: /etc/lamassuiot/config.yml
              subPath: config
            - name: local-crl-file-storage
              mountPath: /data/crl
          ports:
            - containerPort: 8085
      restartPolicy: Always
      volumes:
        - name: api-config
          configMap:  
            name: va-config
  volumeClaimTemplates:
  # If no FileSystem engine is defined, the PVC wont be used
  - metadata:
      name: local-crl-file-storage
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: null
      resources:
        requests:
          storage: 1Gi
