{{- if .Values.services.wfx.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: wfx
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: wfx
  type: ClusterIP
  ports:
  - name: sbi
    port: {{ .Values.services.wfx.clientPort }}
    targetPort: {{ .Values.services.wfx.clientPort }}
    protocol: TCP
  - name: nbi
    port: {{ .Values.services.wfx.managementPort }}
    targetPort: {{ .Values.services.wfx.managementPort }}
    protocol: TCP
{{- end }}
