domain: dev.lamassu.io
debugMode: false
storageClassName: &storage-class-name "" # <----  Default Value

services:
  apiGateway:
    image: lamassuiot/lamassu-gateway-dev:latest
    debugMode: false
  keycloak:
    image: lamassuiot/lamassu-auth-dev:latest
    username: admin
    password: admin
  ui:
    image: lamassuiot/lamassu-ui-dev:latest
  ca:
    image: lamassuiot/lamassu-ca-dev:latest
  deviceManager:
    image: lamassuiot/lamassu-device-manager-dev:latest
    minimumReenrollmentDays: 90
  dmsManager:
    image: lamassuiot/lamassu-dms-manager-dev:latest
  database:
    image: lamassuiot/lamassu-db:v1.0.12
    username: admin
    password: admin
  openPolicyAgent:
    image: openpolicyagent/opa:0.37.1-envoy
  cloudProxy:
    image: lamassuiot/lamassu-cloud-proxy-dev:latest
  rabbitmq:
    image: lamassuiot/lamassu-rabbitmq-dev:latest
  jaeger:
    image: jaegertracing/all-in-one:1.30.0
  alerts:
    image: lamassuiot/lamassu-alerts-dev:latest
    smtp:
      from: ""
      insecure: true
      enable_ssl: true
      username: ""
      password: ""
      host: ""
      port: 25
  awsConnector:
    image: lamassuiot/lamassu-aws-connector-dev:latest
    enabled: false
    name: ""
    aws:
      accessKeyId: ""
      secretAccessKey: ""
      defaultRegion: ""
      sqs:
        inboundQueueName:  ""
        outbountQueueName:  ""

simulationTools:
  enabled: false
  virtualDevice:
    image: lamassuiot/lamassuiot-virtual-device:2.0.0
  virtualDms:
    image: lamassuiot/lamassuiot-virtual-dms:2.0.0

##############################
# Subcharts values
##############################

rabbitmq:
  fullnameOverride: "rabbitmq"
  global:
    storageClass:  *storage-class-name
  auth:
    username: "guest"
    password: "guest"

postgresql-ha:
  fullnameOverride: "postgresql" #If not set, resources are created using Release.Name (referenced in .tpl  as "fullname"). Since it is not possilbe to use Release.Name in .Values.yml file, overwrite to avoid issues
  global:
    storageClass:  *storage-class-name
    postgresql:
      username: "admin"
      password: "admin"
      # database: ""
      repmgrUsername: "admin"
      repmgrPassword: "admin"
      # repmgrDatabase: ""
      existingSecret: ""
  postgresql:
   replicaCount: 3
   initdbScriptsCM: postgres-ha-init

consul:
  fullnameOverride: "consul" #If not set, resources are created using Release.Name (referenced in .tpl  as "fullname"). Since it is not possilbe to use Release.Name in .Values.yml file, overwrite to avoid issues
  global:
    datacenter: lamassu-k8s
  client:
    enabled: false
  server:
    affinity: "null"  #set to null to remove affinity rule. By default consul only deploys 1 service per node. See: https://developer.hashicorp.com/consul/docs/k8s/helm#v-server-affinity
    replicas: 3
    storageClassName: *storage-class-name

vault:
  fullnameOverride: "vault" #If not set, resources are created using Release.Name (referenced in .tpl  as "fullname"). Since it is not possilbe to use Release.Name in .Values.yml file, overwrite to avoid issues
  global:
    tlsDisable: true
  server:
    affinity: ""
    ha:
      enabled: true
      replicas: 3
      apiAddr: http://127.0.0.1:8200
      config: |
        ui = true
        listener "tcp" {
          tls_disable = 1
          address = "0.0.0.0:8200"
          cluster_address = "0.0.0.0:8201"
        }

        storage "consul" {
          path = "vault/"
          address = "consul-server:8500"
        }
  ui:
    enabled: true
  injector:
    enabled: false