postgres:
  hostname: "postgresql"
  port: 5432
  username: "admin"
  password: "admin"

amqp:
  hostname: "rabbitmq"
  port: 5672
  username: "admin"
  password: "admin"
  tls: false
services:
  services:
    ca:
      cryptoEngines:
        defaultEngineID: fs-1
        engines:
          - id: fs-1
            type: filesystem
            storage_directory: /data-fs-1
  apiGateway:
    extraReverseProxyRouting:
      - path: /auth
        name: auth
        prefixRewrite: false
        target:
          host: auth-keycloak
          port: 80  # If no sidecar is used
          healthCheck:
            path: /auth/health
auth:
  oidc:
    frontend:
      authority: https://ci.lamassu.io/auth/realms/lamassu
ingress:
  enabled: true
  domain: ci.lamassu.io
  annotations: |
    kubernetes.io/ingress.class: "public"
