# Intended for helm version 0.21.9
image:
  registry: docker.io
  repository: keycloak/keycloak
  tag: "26.6.2"

service:
  httpPort: 80

keycloak: 
  adminUser: "admin"
  adminPassword: "admin"
  httpRelativePath: /auth
  proxyHeaders: xforwarded

postgres:
  enabled: false

database:
  type: postgres
  host: "postgresql"
  port: "5432"
  username: "admin"
  password: "admin"
  name: auth

extraInitContainers:
  - name: init-custom-theme
    image: curlimages/curl:8.10.1
    command:
    - 'sh'
    - '-c'
    - |
      curl -L -f -o /opt/keycloak/providers/lamassu-theme.jar https://github.com/lamassuiot/keycloak-theme/releases/download/3.0.0/lamassu-theme.jar
    volumeMounts:
    - mountPath: "/opt/keycloak/providers"
      name: keycloak-providers

httpRelativePath: /auth/
proxy: reencrypt
proxyHeaders: xforwarded

extraEnvVars:
  - name: KC_HOSTNAME_STRICT
    value: "false"
  - name: KC_HEALTH_ENABLED
    value: "true"
  - name: KC_SPI_X509CERT_LOOKUP_PROVIDER
    value: "envoy"
  - name: HTTP_ADDRESS_FORWARDING
    value: "true"
  - name: KC_HTTP_ACCESS_LOG_ENABLED
    value: "true"
  - name: KC_HTTP_ACCESS_LOG_PATTERN
    value: combined

realm:
  import: true
  configFile: |
    {
      "realm": "lamassu",
      "enabled": true,
      "loginTheme": "lamassu-theme-v3",
      "roles": {
        "realm": [
          {
            "name": "pki-admin",
            "description": "PKI Full Access"
          }
        ]
      },
      "users": [
        {
          "username": "lamassu",
          "enabled": true,
          "credentials": [
            {
              "type": "password",
              "value": "lamassu",
              "temporary": true
            }
          ],
          "requiredActions": ["UPDATE_PASSWORD"],
          "realmRoles": ["pki-admin"]
        }
      ],
      "clients": [
        {
          "clientId": "frontend",
          "enabled": true,
          "redirectUris": ["/*"],
          "webOrigins": ["/*"],
          "publicClient": true,
          "directAccessGrantsEnabled": true
        }
      ]
    }