# Intended for helm version 16.0.14
fullnameOverride: "rabbitmq"

global:
  security:
    allowInsecureImages: true
    
image:
  registry: docker.io
  repository: bitnamilegacy/rabbitmq
  tag: 4.1.3-debian-12-r1

auth:
  username: admin
  password: admin