{{- if .Values.nethsm.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "soft.nethsm.fullname" . }}-provision
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "soft.labels" . | nindent 4 }}
    app: {{ include "soft.nethsm.fullname" . }}
type: Opaque
stringData:
  unlockPassphrase: {{ .Values.nethsm.provision.unlockPassphrase | quote }}
  adminPassphrase: {{ .Values.nethsm.provision.adminPassphrase | quote }}
  operatorPassphrase: {{ .Values.nethsm.provision.operator.passphrase | quote }}
{{- end }}
