# Default values for softhsm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
image: "ghcr.io/lamassuiot/softhsm:dev"
hsm:
  pin: "1234"
  so_pin: "5432"
  slot: "0"
  label: lamassuHSM
ssh:
  port: 22
  # Set one or more SSH public keys to allow in-cluster SSH tunneling to SoftHSM. Use "ssh-ed25519 XXXXXXXXXXXXXXXX" style
  authorizedKeys: ""
