apiVersion: v2
name: lamassu
description: PKI for Industrial IoT for Kubernetes
type: application
version: 3.8.0
appVersion: 3.8.0
kubeVersion: ">=1.24.0-0"
home: https://lamassu.io
icon: https://avatars.githubusercontent.com/u/27340420?s=200&v=4
keywords:
  - certificate-authority
  - industrial-iot
  - pki
  - security
sources:
  - https://github.com/lamassuiot
  - https://github.com/lamassuiot/lamassu-kubernetes-chart
maintainers:
  - name: lamassuiot
    url: https://github.com/lamassuiot
annotations:
  artifacthub.io/category: security
  artifacthub.io/license: MPL-2.0
  artifacthub.io/links: |
    - name: Documentation
      url: https://github.com/lamassuiot/lamassu-helm
    - name: Support
      url: https://github.com/lamassuiot/lamassu-helm/issues
