domain: &DOMAIN dev.lamassu.io
logLevel: 0  # 0 -> INFO, 1 -> DEBUG, 2 -> TRACE
debugMode: true

# Downstream TLS
tls:
  type: letsEncrypt | external
  letsEncryptOptions:
    clusterIssuer: ""
    issuer: ""
    selfSignedOptions:
      duration: "2160h"  # 2160h == 90days
  externalOptions:
    secretName: ""

ingress:
  annotations: |

postgres:
  hostname: ""
  port: 5432
  username: ""
  password: ""

amqp:
  hostname: ""
  port: 5672
  username: ""
  password: ""
  tls: false

auth:
  oidc:
    frontend:
      clientId: "frontend"
      authority: https://${window.location.hostname}/auth/realms/lamassu
      awsCognito:
        enabled: false
        hostedUiDomain: ""
    apiGateway:
      jwksUrl: https://auth:8443/auth/realms/lamassu/protocol/openid-connect/certs
  authorization:
    rolesClaim: realm_access.roles
    roles:
      admin: pki-admin
      operator: operator

services:
  keycloak:
    enabled: true
    image: ghcr.io/lamassuiot/keycloak:2.1.0
    adminCreds:
      username: "admin"
      password: "admin"
  ui:
    image: ghcr.io/lamassuiot/lamassu-ui:2.5.0
  va:
    image: ghcr.io/lamassuiot/lamassu-va:2.5.0
  ca:
    image: ghcr.io/lamassuiot/lamassu-ca:2.5.0
    monitoring:
      frequency: "* * * * *"
    engines:
      defaultEngineID: "golang-1"
      golang:
        - id: "golang-1"
          storage_directory: "/data"
          metadata:
            prod-ready: "false"
      awsKms:
      awsSecretsManager:
      pkcs11:
      hashicorpVault:
  deviceManager:
    image: ghcr.io/lamassuiot/lamassu-devmanager:2.5.0
    minimumReenrollmentDays: 100
  dmsManager:
    image: ghcr.io/lamassuiot/lamassu-dmsmanager:2.5.0
  openPolicyAgent:
    image: openpolicyagent/opa:0.37.1-envoy
    remLogger:
      image: ghcr.io/lamassuiot/opa-rem-logger:2.1.0
  alerts:
    image: ghcr.io/lamassuiot/lamassu-alerts:2.5.0
    smtp_server:
      from: ""
      insecure: false
      enable_ssl: true
      username: ""
      password: ""
      host: ""
      port: 25
  awsConnector:
    enabled: false
    image: ghcr.io/lamassuiot/lamassu-aws-connector:2.5.0
    connectorID: "aws.XXXXXXXXX"
    credentials:
      accessKeyId: ""
      secretAccessKey: ""
      defaultRegion: ""

simulationTools:
  enabled: false
  virtualDevice:
    image: lamassuiot/lamassuiot-virtual-device:2.0.0
  virtualDms:
    image: lamassuiot/lamassuiot-virtual-dms:2.0.0
