kind: ConfigMap
apiVersion: v1
metadata:
  name: auth-init
  namespace: {{.Release.Namespace}}
data:
  users-create-script.sh: |
    # apt-get update
    # apt-get install curl jq -y

    # Check if Auth is healthy

    echo "Waiting Auth to launch on 8080..."
    until $(curl -s -o /dev/null -f http://auth:8080/auth/ -I | grep HTTP | awk '{print $2}'); do
      printf '.'
      sleep 1
    done
    sleep 60
    echo "Auth is launched"

    
    opt/jboss/keycloak/bin/kcadm.sh config credentials --server http://auth:8080/auth --realm master --user admin --password admin

    # Create enroller
    opt/jboss/keycloak/bin/kcadm.sh create users -s username=enroller -s enabled=true -r lamassu
    opt/jboss/keycloak/bin/kcadm.sh set-password -r lamassu --username=enroller --new-password enroller
    opt/jboss/keycloak/bin/kcadm.sh add-roles --uusername enroller --rolename admin -r lamassu

    # Create operator
    opt/jboss/keycloak/bin/kcadm.sh create users -s username=operator -s enabled=true -r lamassu
    opt/jboss/keycloak/bin/kcadm.sh set-password -r lamassu --username=operator --new-password operator

    #Terminate IstioProxy: https://github.com/istio/istio/issues/6324#issuecomment-533923427
    curl -sf -XPOST http://127.0.0.1:15020/quitquitquit