apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
  namespace: {{.Release.Namespace}}
  labels:
    app: auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: {{.Values.services.keycloak.image}}
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
            - containerPort: 8443
          env:
            - name: DB_VENDOR
              value: postgres
            - name: DB_ADDR
              value: postgresql-pgpool #Service Name for HA postgres
            - name: DB_DATABASE
              value: auth
            - name: DB_USER
              value: {{.Values.services.database.username}}
            - name: DB_PASSWORD
              value: {{.Values.services.database.password}}
            - name: KEYCLOAK_USER
              value: {{.Values.services.keycloak.password}}
            - name: KEYCLOAK_PASSWORD
              value: {{.Values.services.keycloak.password}}
            - name: KEYCLOAK_IMPORT
              value: /tmp/lamassu.json
            - name: PROXY_ADDRESS_FORWARDING
              value: "true"
            - name: REDIRECT_SOCKET
              value: proxy-https
            - name: KEYCLOAK_FRONTEND_URL
              value: https://auth.{{.Values.domain}}/auth
      restartPolicy: Always