apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: default
  namespace: {{.Release.Namespace}}
spec:
  hosts:
    - "*"
  gateways:
    - default-gateway
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        port:
          number: 443
        host: default-traffic-manager