apiVersion: v1
kind: Service
metadata:
  name: device-manager
  namespace: {{.Release.Namespace}}
spec:
  selector:
    app: device-manager
  type: ClusterIP
  ports:
  - name: https
    port: 8085
    targetPort: 8085
    protocol: TCP