apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{.Release.Namespace}}-{{.Release.Names}}-root-downstream-cert
  namespace: istio-system
spec:
  isCA: true
  commonName: "downstream-selfsigned-cert"
  secretName: {{.Release.Namespace}}-{{.Release.Names}}-root-downstream-cert
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: selfsigned-issuer
    kind: Issuer
    group: cert-manager.io