kind: ConfigMap
apiVersion: v1
metadata:
  name: ui-nginx-config
  namespace: {{.Release.Namespace}}
data:
  config: |
    server {
      listen 80;
      server_name webapp;

      root /usr/share/nginx/html;
      index index.html index.htm;      

      location ~* \.(?:manifest|appcache|html?|xml|json)$ {
        expires -1;
        # access_log logs/static.log; # I don't usually include a static log
      }

      location ~* \.(?:css|js)$ {
        try_files $uri =404;
        expires 1y;
        access_log off;
        add_header Cache-Control "public";
      }
      # Any route that doesn't have a file extension (e.g. /devices)
      location ~ ^/ {
        try_files $uri $uri/ /index.html;
      }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:  
  name: ui
  namespace: {{.Release.Namespace}}
  labels:
    app: ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ui
  template:
    metadata:
      labels:
        app: ui
    spec:     
      containers:
        - name: ui
          image: {{.Values.services.ui.image}}
          imagePullPolicy: Always
          env:
            - name: DOMAIN
              value: {{.Values.domain}}
            - name: REACT_APP_AUTH_ENDPOINT
              value: "https://auth.{{.Values.domain}}/auth"
            - name: REACT_APP_AUTH_REALM
              value: "lamassu"
            - name: REACT_APP_AUTH_CLIENT_ID
              value: "frontend"
            - name: REACT_APP_LAMASSU_CLOUD_PROXY_API
              value: "https://{{.Values.domain}}/api/cloudproxy"
            - name: REACT_APP_LAMASSU_CA_API
              value: "https://{{.Values.domain}}/api/ca"
            - name: REACT_APP_LAMASSU_DMS_ENROLLER_API
              value: "https://{{.Values.domain}}/api/dmsenroller"
            - name: REACT_APP_LAMASSU_DEVMANAGER
              value: "https://{{.Values.domain}}/api/devmanager"
          volumeMounts:          
            - name: nginx-config
              mountPath: /etc/nginx/conf.d/server.conf
              subPath: config
      restartPolicy: Always
      volumes:
        - name: nginx-config
          configMap:
            name: ui-nginx-config