apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: vault-init
  namespace: {{.Release.Namespace}}
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs: ["create"]
  - apiGroups:
      - ""
    resources:
      - endpoints
    verbs: ["get", "list", "watch"]