{{- if .Values.simulationTools.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:  
  name: virtual-device
  namespace: {{.Release.Namespace}}
  labels:
    app: virtual-device
spec:
  replicas: 1
  selector:
    matchLabels:
      app: virtual-device
  template:
    metadata:
      labels:
        app: virtual-device
    spec:
      containers:
        - name: virtual-device
          image: {{.Values.simulationTools.virtualDevice.image}}
          env:
            - name: VDMS_ADDRESS
              value: http://virtual-dms:7002
            - name: LAMASSU_GATEWAY 
              value: https://{{.Values.domain}}
            - name: AWS_IOT_ENDPOINT 
              value: "a"
            - name: AWS_IOT_CA
              value: /app/aws-iotcore-ca.crt
            - name: AZURE_IOT_HUB_ENDPOINT 
              value: "a"
            - name: AZURE_DPS_ENDPOINT 
              value: "a"
            - name: AZURE_SCOPE_ID 
              value: "a"
            - name: AZURE_IOT_HUB_CA 
              value: "/app/azure-iothub-ca.crt"
          ports:
            - containerPort: 7001
      restartPolicy: Always
{{- end }}