{{- if .Values.simulationTools.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:  
  name: virtual-dms
  namespace: {{.Release.Namespace}}
  labels:
    app: virtual-dms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: virtual-dms
  template:
    metadata:
      labels:
        app: virtual-dms
    spec:
      containers:
        - name: virtual-dms
          image: {{.Values.simulationTools.virtualDms.image}}
          env:
            - name: LAMASSU_GATEWAY 
              value: https://{{.Values.domain}}
          ports:
            - containerPort: 7002
      restartPolicy: Always
{{- end }}