{{- if .Values.simulationTools.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: virtual-device
  namespace: {{.Release.Namespace}}
spec:
  selector:
    app: virtual-device
  type: ClusterIP
  ports:
  - name: https
    port: 7001
    targetPort: 7001
    protocol: TCP
{{- end }}