name: Fast lane Test

on: workflow_dispatch

jobs:
  fast-lane-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: azure/setup-kubectl@v3
      - name: Set up Helm
        uses: azure/setup-helm@v4.0.0
        with:
          version: v3.12.1
      - name: Create kind cluster
        uses: helm/kind-action@v1.9.0
        with:
          name: lamassu-ci-cluster
      - name: Prepare kind cluster
        run: |
          kubectl apply -f https://github.com/cert-manager/cert-manager/releases/download/v1.14.3/cert-manager.yaml
      - name: run fast lane
        run: |
          ./scripts/lamassu-fast-lane.sh -n -ns lamassu-ci -d ci.lamassu.io
      - name: show info
        run: |
          kubectl get pods -n lamassu-ci
          kubectl get svc -n lamassu-ci
          kubectl get ingress -n lamassu-ci