name: Fast lane Test

permissions:
  contents: read

on: workflow_dispatch

jobs:
  fast-lane-test:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0
      - name: Add hosts to /etc/hosts
        run: |
          VM_IP=$(hostname -I | awk '{print $1}')
          sudo echo "$VM_IP ci.lamassu.io" | sudo tee -a /etc/hosts
      - uses: azure/setup-kubectl@3e0aec4d80787158d308d7b364cb1b702e7feb7f # v4.0.0
      - name: Set up Helm
        uses: azure/setup-helm@fe7b79cd5ee1e45176fcad797de68ecaf3ca4814 # v4.2.0
        with:
          version: v3.12.1
      - name: Create kind cluster
        uses: helm/kind-action@a1b0e391336a6ee6713a0583f8c6240d70863de3 # v1.12.0
        with:
          config: .github/ci/kind.yaml
      - name: Prepare kind cluster
        run: |
          kubectl apply -f https://github.com/cert-manager/cert-manager/releases/download/v1.20.2/cert-manager.yaml --wait
          helm install eg oci://docker.io/envoyproxy/gateway-helm --version v1.8.0 -n envoy-gateway-system --create-namespace -f .github/ci/eg.yaml --wait
          cat <<EOF | kubectl apply -f -
            apiVersion: gateway.networking.k8s.io/v1
            kind: GatewayClass
            metadata:
              name: eg
            spec:
              controllerName: gateway.envoyproxy.io/gatewayclass-controller
          EOF
          kubectl wait --timeout=5m -n envoy-gateway-system deployment/envoy-gateway --for=condition=Available
                
          kubectl create namespace lamassu-ci
      - name: Run fast lane
        run: |
          ./scripts/lamassu-fast-lane.sh -n -ns lamassu-ci -d ci.lamassu.io -l ./charts/lamassu
      - name: Show info
        run: |
          kubectl get pods -A
          kubectl get svc -A
          kubectl get gtw -A
      - name: Run helm tests
        run: |
          helm test -n lamassu-ci lamassu --logs